"use client";
import { FormEvent, useState } from "react";
import { useMutation,useQuery,useQueryClient } from "@tanstack/react-query";
import { toast } from "sonner";
import { canAdmin,useAuth } from "@/hooks/use-auth";
import { createSource,getOperations,replaceSource,SourceRecord,SourceWrite,testSource,updateSource } from "@/services/operations";

const capabilityLabels:Record<string,string>={competitions:"البطولات",fixtures:"المباريات",teams:"الفرق",standings:"الترتيب",predictions:"التوقعات",news:"الأخبار والمعلومات"};
const empty:SourceWrite={code:"",name:"",source_type:"api",provider:"football_data",base_url:"https://api.football-data.org/v4",priority:50,capabilities:["competitions","fixtures","teams","standings"],enabled:true};

export default function SourcesPage(){
  const{user}=useAuth();const qc=useQueryClient();const[editing,setEditing]=useState<SourceRecord|null>(null);const[form,setForm]=useState<SourceWrite>(empty);
  const q=useQuery({queryKey:["operations"],queryFn:getOperations,refetchInterval:15000});
  const refresh=()=>qc.invalidateQueries({queryKey:["operations"]});
  const toggle=useMutation({mutationFn:({id,enabled}:{id:string;enabled:boolean})=>updateSource(id,enabled),onSuccess:refresh,onError:e=>toast.error(e.message)});
  const save=useMutation({mutationFn:(value:SourceWrite)=>editing?replaceSource(editing.id,value):createSource(value),onSuccess:()=>{toast.success("تم حفظ المصدر");setEditing(null);setForm(empty);refresh()},onError:e=>toast.error(e.message)});
  const test=useMutation({mutationFn:testSource,onSuccess:r=>r.ok?toast.success("الاتصال بالمصدر ناجح"):toast.error("فشل اختبار الاتصال بالمصدر"),onError:e=>toast.error(e.message)});
  const edit=(s:SourceRecord)=>{setEditing(s);setForm({code:s.code,name:s.name,source_type:s.source_type,provider:s.provider,base_url:s.base_url,priority:s.priority,capabilities:s.capabilities,enabled:s.enabled})};
  const submit=(event:FormEvent)=>{event.preventDefault();if(!canAdmin(user?.role))return;save.mutate(form)};
  return <div className="space-y-6"><header className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-sm text-cyan-700">المزودون الفعليون</p><h1 className="text-3xl font-black">مصادر البيانات</h1></div>{canAdmin(user?.role)&&<button className="rounded-xl bg-cyan-700 px-4 py-2 text-white" onClick={()=>{setEditing(null);setForm(empty)}}>إضافة مصدر</button>}</header>
    {canAdmin(user?.role)&&<form onSubmit={submit} className="grid gap-3 rounded-2xl border bg-white p-5 dark:bg-slate-950 md:grid-cols-2"><h2 className="font-bold md:col-span-2">{editing?"تعديل المصدر":"إضافة مصدر"}</h2><label>الرمز<input required pattern="[a-z][a-z0-9_]{1,49}" value={form.code} onChange={e=>setForm({...form,code:e.target.value})} className="mt-1 w-full rounded-lg border p-2"/></label><label>الاسم<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})} className="mt-1 w-full rounded-lg border p-2"/></label><label>النوع<select value={form.source_type} onChange={e=>setForm({...form,source_type:e.target.value})} className="mt-1 w-full rounded-lg border p-2"><option value="api">API</option><option value="official_site">موقع رسمي</option><option value="news">أخبار</option><option value="manual">يدوي</option></select></label><label>المزوّد<select value={form.provider??""} onChange={e=>setForm({...form,provider:e.target.value||null})} className="mt-1 w-full rounded-lg border p-2"><option value="">لا يوجد</option><option value="football_data">football_data</option><option value="api_football">api_football</option></select></label><label className="md:col-span-2">Base URL<input type="url" value={form.base_url??""} onChange={e=>setForm({...form,base_url:e.target.value||null})} className="mt-1 w-full rounded-lg border p-2" placeholder="https://..."/></label><label>الأولوية<input type="number" min="0" max="100" value={form.priority} onChange={e=>setForm({...form,priority:Number(e.target.value)})} className="mt-1 w-full rounded-lg border p-2"/></label><label>مفتاح API جديد (اختياري)<input type="password" autoComplete="new-password" onChange={e=>setForm({...form,secret:e.target.value||undefined})} className="mt-1 w-full rounded-lg border p-2"/><small>اتركه فارغًا للإبقاء على المفتاح الحالي. لن تُعاد قيمته إلى المتصفح.</small></label><fieldset className="md:col-span-2"><legend>أنواع البيانات</legend><div className="flex flex-wrap gap-3">{Object.entries(capabilityLabels).map(([key,label])=><label key={key}><input type="checkbox" checked={form.capabilities.includes(key)} onChange={e=>setForm({...form,capabilities:e.target.checked?[...form.capabilities,key]:form.capabilities.filter(x=>x!==key)})}/> {label}</label>)}</div></fieldset><div className="flex gap-2 md:col-span-2"><button disabled={save.isPending} className="rounded-lg bg-cyan-700 px-4 py-2 text-white">حفظ</button>{editing&&<button type="button" onClick={()=>{setEditing(null);setForm(empty)}} className="rounded-lg border px-4 py-2">إلغاء</button>}</div></form>}
    <div className="grid gap-4 md:grid-cols-2">{q.data?.sources.map(s=><article key={s.id} className="rounded-2xl border bg-white p-5 dark:bg-slate-950"><div className="flex justify-between gap-3"><div><h2 className="font-bold">{s.name}</h2><code>{s.code}</code><p className="text-xs text-muted-foreground">{s.source_type} · أولوية {s.priority} · المفتاح {s.secret_configured?"مضبوط":"غير مضبوط"}</p></div><button disabled={!canAdmin(user?.role)} onClick={()=>window.confirm(`${s.enabled?"تعطيل":"تفعيل"} المصدر؟`)&&toggle.mutate({id:s.id,enabled:!s.enabled})} className={`rounded-full px-3 py-1 text-sm ${s.enabled?"bg-emerald-100 text-emerald-800":"bg-slate-200"}`}>{s.enabled?"مفعّل":"متوقف"}</button></div><p className="mt-3 break-all text-xs" dir="ltr">{s.base_url}</p><p className="mt-2 text-sm">{s.capabilities.map(x=>capabilityLabels[x]??x).join("، ")||"لا توجد قدرات محددة"}</p><dl className="mt-5 grid grid-cols-2 gap-3 text-sm"><div><dt className="text-muted-foreground">آخر نجاح</dt><dd>{s.last_success_at?new Date(s.last_success_at).toLocaleString("ar-IQ",{timeZone:"Asia/Baghdad"}):"لا يوجد"}</dd></div><div><dt className="text-muted-foreground">آخر فشل</dt><dd>{s.last_failure_at?new Date(s.last_failure_at).toLocaleString("ar-IQ",{timeZone:"Asia/Baghdad"}):"لا يوجد"}</dd></div></dl>{canAdmin(user?.role)&&<div className="mt-4 flex gap-2"><button onClick={()=>edit(s)} className="rounded-lg border px-3 py-2">تعديل</button><button onClick={()=>test.mutate(s.id)} className="rounded-lg border px-3 py-2">اختبار الاتصال</button></div>}</article>)}</div></div>}
